### ISSUE TITLE
Remove stage-0 from babelrc config in package.json

### ISSUE THREAD

**Issue by Joelkang** [aholachek/react-flip-toolkit#1]
Hey @aholachek, great library! I just dropped it into my https://github.com/bvaughn/react-virtualized `Grid` and it Just Worked™!

I was, noticing that you had this in the babel config though: do we really need it? I scanned through the code and it doesnt seem like there's any stage 0 code in there
https://github.com/aholachek/react-flip-toolkit/blob/47c442ef2023d3c72edfb0d0a0e92e31b19a34da/package.json#L47

**Comment by aholachek** [comment]
Thanks for pointing this out. This config was just for jest (I use the nwb module bundler which handles babel compilation for the library separately). I've moved the babel config into its own `jest.transform.js` file and removed the unnecessary `stage-0` that you found
