### ISSUE TITLE
Version 7.0.8 pulls in the entire @emotion toolchain

### ISSUE THREAD

**Issue by raibima** [aholachek/react-flip-toolkit#114]
Hi @aholachek, not sure if this is expected but I just noticed the v7.0.8 on npm pulls in @emotion toolchain.

## Repro
```bash
mkdir my-project
yarn init -y
yarn add react-flip-toolkit
```

Tried to inspect the content of node_modules, I saw the following in this library's dependencies:
```json
"dependencies": {
  "@emotion/core": "^10.0.27",
  "react": ">=16.3.0",
  "rematrix": "0.2.2"
},
```

Notes:
* Doesn't happen on v7.0.7 and below.
* We should probably remove `react` from the dependencies as well

**Comment by aholachek** [comment]
Hi @raibima ,
Thank you for flagging! I believe this is the second time those dependencies have been automatically inserted by something, so I need to dig deeper into what happened, but in the meantime, [I've published a patch that should remove the unused dependencies](https://unpkg.com/react-flip-toolkit@7.0.9/package.json)

**Comment by raibima** [comment]
thanks! I have verified the latest version no longer has this issue 👍
