### ISSUE TITLE
onExit not working, nodes have already vanished?

### ISSUE THREAD

**Issue by learis** [aholachek/react-flip-toolkit#119]
This happened today and I cannot figure out why. Everything was working fine for weeks, but now my "fadeout" animation from my onExit callback is gone. I follow the simple example of adding a class which initiates a fadeout animation, and then have a timeout to call the removeElement function afterwards. But now the nodes just instantly disappear. There is no animation and just a waiting for the timeout to finish. It's hard to debug, but the best I can tell is that all of the nodes have already disappeared by the time onExit is being called. So any logic in there to animate a fadeout via adding a class does absolutely nothing because the nodes have instantly disappeared. Oddly enough, onAppear still works just fine. My app is complicated and I don't think I could reproduce this on codeSandbox. Does anyone have any ideas on what could cause nodes to already be gone by the time onExit is called? Maybe something to do with how react updates to the DOM occur?

**Comment by learis** [comment]
Please disregard this issue. It ofcourse is my error. Between my Flipper and my Flipped elements I have some "middle-man" div's. I made poor choices in the key property that I gave to these divs which resulted in them re-rendering during state updates when they absolutely should not have re-rendered. Their unwanted re-renders screwed up my onExit calls. This effectively is what caused my problem. Lesson learned.

**Comment by aholachek** [comment]
Thanks for the follow up!
