### ISSUE TITLE
Make prop-types a direct dependency

### ISSUE THREAD

**Issue by jraoult** [aholachek/react-flip-toolkit#121]
Following the official advice would you consider putting prop-types in the dependencies list cf. https://github.com/facebook/prop-types#how-to-depend-on-this-package.

I ended installing it as a dependency in my app (even if I don't actually use them) just so that _yarn_ stops to complain and _dependabot_ doesn't skip `react-flip-toolkit` upgrade because the peer dep is missing.

Thanks for the fantastic lib by the way 👏.

**Comment by aholachek** [comment]
Thanks, I wasn't aware of this recommendation. I'll release a patch update this week that fixes this.

**Comment by aholachek** [comment]
Released in 7.0.10! It looks like tools like bundlephobia now count proptypes as contributing to increased bundle size: https://bundlephobia.com/result?p=react-flip-toolkit@7.0.10, which is a bit of a shame since the actual bundle size wasn't affected by this change.

**Comment by jraoult** [comment]
@aholachek oh thanks for the quick turnaround!

> which is a bit of a shame since the actual bundle size wasn't affected by this change.

Yeah, this a limit of the bundlephobia reports. They give you the worst-case scenario which is often not the actual impact on the app. To be fair, a quick look at the other animation libraries for react on bundlephobia shows that they are including `prop-types` as well, so the comparison (even with this offset) still makes sense.

**Comment by aholachek** [comment]
Good point. I'll close this issue but feel free to reopen if it didn't fix the issue, and thanks again for flagging it.
