### ISSUE TITLE
Dependency was not found

### ISSUE THREAD

**Issue by Nero-t** [aholachek/react-flip-toolkit#124]
Hello,

I want to use flip-toolkit (whitout react) so I do :

npm install flip-toolkit
then
import { Flipper } from 'flip-toolkit' 

And i have this problem :

<img width="634" alt="Capture d’écran 2020-06-08 à 12 48 08" src="https://user-images.githubusercontent.com/66620825/84023113-cd674e00-a987-11ea-9013-0c7d786cefe6.png">

But i have both folders in my node_modules : flip-toolkit and react-flip-toolkit
<img width="298" alt="Capture d’écran 2020-06-08 à 12 59 51" src="https://user-images.githubusercontent.com/66620825/84023251-0b647200-a988-11ea-991b-9263603c24af.png">
<img width="288" alt="Capture d’écran 2020-06-08 à 13 00 17" src="https://user-images.githubusercontent.com/66620825/84023261-0ef7f900-a988-11ea-8d3d-4d038bff4fdc.png">

I'm using Symfony 4.4 and bundle Encore for the assets.

Sorry for asking this issue and thanks a lot for the help.

**Comment by aholachek** [comment]
Hi @Nero-t, thanks for making this issue! You caught a bug. Can you try `flip-toolkit@7.0.11` and see if it resolves this problem?

**Comment by Hugo-22** [comment]
Hello @aholachek and I will thank you very much ! 

Bug fix  with `flip-toolkit@7.0.11`

**Comment by Nero-t** [comment]
Hello @aholachek, I will thank you very much !

Bug fix with `flip-toolkit@7.0.11`
