### ISSUE TITLE
Can't figure out how to animate last item.

### ISSUE THREAD

**Issue by lifeiscontent** [aholachek/react-flip-toolkit#130]
Hey @aholachek first off, thanks for this great library.

I was wondering if you could give me some insight on how to handle some of these edge cases I'm seeing.

1. if you add the first item to the list, it doesn't animate in.

2. is there a way to remove the container if there are no elements left without breaking the lifecycle of the animation sequence?

https://codesandbox.io/s/quirky-waterfall-gn8xj?file=/src/App.js

Thanks!

**Comment by aholachek** [comment]
Hi, for  question 1, you'd need to create an animation yourself using the `onAppear` prop of `Flipped`,  something like  this: https://codesandbox.io/s/sleepy-water-eessr?file=/src/App.js
For question 2, I'm not sure I fully understand but it doesn't sound like something that would work -- if you remove the container you will immediately remove all elements inside of it.
