### ISSUE TITLE
React-native support?

### ISSUE THREAD

**Issue by itxtoledo** [aholachek/react-flip-toolkit#137]
I would like to know from you if this library works in react-native. I've been using it in ReactJS and I would like to use it in my App

**Comment by aholachek** [comment]
Hello, react-flip-toolkit was not made with react-native in mind so I would be surprised if it worked seamlessly, but I have not tried it or heard of anyone who has tried it.

**Comment by gaillota** [comment]
I just tested it out and it doesn't work. `react-flip-toolkit` has some hardcoded `div` in its codebase which is incompatible with `react-native`
