### ISSUE TITLE
Spring explorer repo doesn't work

### ISSUE THREAD

**Issue by TomasSestak** [aholachek/react-flip-toolkit#138]
https://codepen.io/aholachek/pen/bKmZbV

I have only blank space

**Comment by aholachek** [comment]
Thanks for the heads up! This has been fixed.

**Comment by aholachek** [comment]
(I guess just to be clear i should clarify that I changed the link in the readme to this codesandbox instead of the old codepen: https://codesandbox.io/s/react-flip-toolkit-spring-settings-explorer-vjrsh)
