### ISSUE TITLE
Permission to fork demos 

### ISSUE THREAD

**Issue by ZachSaucier** [aholachek/react-flip-toolkit#141]
Hey Alex. Would you mind if we at GreenSock used a couple of demos based on some of the demos for this library for our upcoming Flip plugin? Our JS implementation is quite different and makes use of GSAP, but we used some of the demos listed for your tool to test different aspects of our plugin and we'd like to show those demos to others.

Keep up the great work! And lovely personal site by the way.

**Comment by aholachek** [comment]
Hey, thanks for asking! Feel free to take whichever demos might be helpful.
