### ISSUE TITLE
Nothing is happening

### ISSUE THREAD

**Issue by ai** [aholachek/react-flip-toolkit#18]
Sorry, I came with the hardest issue “I added a library, but there is no any animation”. 

It is definitely because I didn’t understand something or made some stupid mistake. But it could be a good opportunity to improve the docs or add a warning =^_^=.

I added FLIP toolkit to our popups.

```js
render () {
    let last = this.props.popups.length - 1
    let currentPopup = this.props.popups[last] || { }
    return <Flipper flipKey={JSON.stringify(currentPopup)}>{
       this.props.popups.map(popup => {
         <Flipped flipId={JSON.stringify(popup)}>
           <span>
             <Popup data={ popup }></Popup>
           </span>
         </Flipped>
       })
    </Flipper>
}
```

Here is a link, which will open a popup:

```js
  render () {
    return <Flipped flipId={JSON.stringify(popup)}>
      <span>
        <Tile></Tile>
      </span>
    </Flipped>
  }
```

> Make sure you're updating the flipKey attribute in the Flipper component whenever an animation should happen.

Tested, `flipKey` is updating every time, when popup opens/closes (the popup link will add new `popup` description object to `this.props.popups`).

> If one of your Flipped components is wrapping another React component rather than a DOM element, make sure that component passes down unknown props directly to its DOM element

I checked Chrome DevTools and link and popup has `data` attributes

```
<span data-flip-id="{&quot;type&quot;:&quot;links&quot;,&quot;projectId&quot;:1}" data-flip-config="{&quot;translate&quot;:true,&quot;scale&quot;:true,&quot;opacity&quot;:true}">
```

What else I can check?

**Comment by aholachek** [comment]
Hi! I definitely need to put a little more work into the Readme, hopefully this is just a misunderstanding and not a bug.

If I understand correctly, you want to transition the `Tile` link component into the `Popup` component itself.

As the first thing I thought of, do you know if the `Flipper` component is high enough in the tree that it is persistent and remains over the course of the animation? You need a single `Flipper` component that wraps both the popups array component and the popup link component to manage the transition. Basically, all related `Flipped` components need a single, stable `Flipper` parent.
From what I see in the JSX you posted, it looks like that might not be the case? I see the `Flipper` container only surrounding the `Popups` array, not the `Tile` component. 

But if this is off base, please let me know and I can think harder about it.

**Comment by ai** [comment]
> I definitely need to put a little more work into the Readme

I hope I can help you with it. I really like the project and want to spread it and spread animations.

> you want to transition the Tile link component into the Popup component itself.

Yeap

> As the first thing I thought of, do you know if the Flipper component is high enough

Yeap. Sorry, I missed it. Flipper wrap all popups *and* main page (with Tile).

```js
render () {
    let last = this.props.popups.length - 1
    let currentPopup = this.props.popups[last] || { }
    return <Flipper flipKey={JSON.stringify(currentPopup)}>{
       this.props.popups.map(popup => {
         <Flipped flipId={JSON.stringify(popup)}>
           <span>
             <Popup data={ popup }></Popup>
           </span>
         </Flipped>
       }).concat([
         <Page>{ this.props.children }</Page>
       ])
    </Flipper>
}
```

**Comment by aholachek** [comment]
Hmm I'm not sure. I tried to make [a minimal test case here](https://codepen.io/aholachek/pen/xarrPQ?editors=0110),  and it errors out with JSON as a flipId because I guess that's not a valid selector. Could you try using a simple string as a flipId instead and see if that helps? I don't know if you are seeing the same error on your end though.

**Comment by ai** [comment]
Replacing `flipId` to simple string didn’t help.

I will try to just go into the code and debug it line-by-line. Maybe it will be better to heavy environment related bugs.

**Comment by aholachek** [comment]
Thank you for taking the time to figure out what was happening. I made the same "duplicate elements" mistake a few times when I was writing the library.

I [added a console warning](https://github.com/aholachek/react-flip-toolkit/blob/v4.0.7/src/flip/animateFlippedElements/index.js#L164), as you suggested, which will hopefully make things clearer for people in the future. It's [briefly mentioned in the docs as well](https://github.com/aholachek/react-flip-toolkit#problem-2-things-look-weird), all the way at the bottom, but the warning is more user-friendly. 

Thank you again for your contributions!

**Comment by ai** [comment]
Wow, it was very quick 👍
