### ISSUE TITLE
Cannot find any packaged version beyond v6.6.5 for use in a script tag

### ISSUE THREAD

**Issue by tkriplean** [aholachek/react-flip-toolkit#192]
Thanks for this project!

I'm trying to find a packaged version of react-flip-toolkit / flip-toolkit that I can include in my web app via a script tag.

It appears that sometime around v6.6.5, the UMD builds stopped being compiled & packaged. Here's the last place I can find it: https://unpkg.com/browse/react-flip-toolkit@6.6.5/ (after following the guidance in #9). I haven't been able to find any script-ready builds for the v7 series. 

I may very well be missing something completely obvious, but I've been looking for hours and feel like I'm at a deadend. Do I need to compile one myself? Any guidance would be greatly appreciated.

Thanks again!

**Comment by tkriplean** [comment]
For anyone else for whom this issue affects, the v6.6.5 files are working for me in a React 18 application.

**Comment by aholachek** [comment]
Hi @tkriplean, sorry for the delay in response. I just published v7.0.16, which fixes a bundler misconfiguration that broke UMD builds [(working demo here).](https://codepen.io/aholachek/pen/ERRpEj). Hopefully that should resolve the problem and thanks for raising this issue,

**Comment by tkriplean** [comment]
Thank you @aholachek!
