### ISSUE TITLE
Unknown event handler property `onexit`. It will be ignored.

### ISSUE THREAD

**Issue by madwill** [aholachek/react-flip-toolkit#2]
First of all thank you for such a great library, its beautiful and really easy to use. 

Second sorry to ask here but I'm not sure where to. 

Following the given example I tried to add the onExit callback for the Flipped element and somehow, it appears onExit gets lowercased into onexit and triggers a React warning that it will be ignored. 

There is a good chance that the problem is from me but it appears I can not figure it out. 

```
<ul className="list">
  {slicedData.map((product, i) => (
    <Flipped flipId={product.id} key={i + 'id'} onExit={onExit} onAppear={this.onElementAppear} >
	 <li  key={product.id}><ProductCardWithPopup product={product} /></li>
    </Flipped>
	))}
</ul>
```
This creates this error. 

> index.js:2178 Warning: Unknown event handler property `onexit`. It will be ignored.
>     in li (created by ProductList)
>     in Flipped
>     in FlippedWithContext (at Shop.js:129)
>     in ul (at Shop.js:127)
>     in main (at Shop.js:114)
>     in div (created by Flipper)
>     in Flipper (at Shop.js:109)
>     in ProductList (at Shop.js:39)
>     in div (created by GridColumn)
>     in GridColumn (at Shop.js:38)
>     in div (created by GridRow)
>     in GridRow (at Shop.js:34)
>     in div (created by Grid)
>     in Grid (at Shop.js:33)
> 

Thank you so very much if you can help. If its not the place for help you can close this issue and i will not use onExit for now. 

Version used is 3.0.4

**Comment by aholachek** [comment]
Thank you for making an issue! I'm puzzled by this one so I will have to dig into it tonight. 

As long as it's on the `Flipped` component, the `onExit` prop should never make its way onto the `li`, you can see [a codepen demo with `onExit` callbacks on `li` elements here](https://codepen.io/aholachek/pen/gKjYNw?editors=0110) that works properly.

**Comment by madwill** [comment]
Yes! your example do work! 

For what its worth I used CRA to make the initial boilerplate. I'm starting to think it has to do with the transformation of JSX. 

For example onAppear does not create this issue, I also used onComplete to test and did not get an issue as well. 

But as soon as i use onExit it gets lowercased and throw this error. I'll let you know if i find anything else. 

Thanks again! This makes my prototype looks so cool I can't believe it :)

**Comment by madwill** [comment]
Yep, pretty sure it makes it to the `li` because it gets transformed into lowercase and you are using the spread operator on `rest`. Since you pull onExit, onexit goes through. 

Why would that happen is still a mystery. Bet if i change it to onRemove it'll work. But that is Voodoo troubleshooting.

**Comment by madwill** [comment]
So i did change it to onRemove and it works without the warning in Create React App. If i figure out why onExit gets transformed into lowercase i'll let you know!

**Comment by aholachek** [comment]
I've been on the lookout to try to reproduce this and haven't been able to yet. I'll close this (for now).
