### ISSUE TITLE
List Reorder, wait till element is removed

### ISSUE THREAD

**Issue by marjan2k** [aholachek/react-flip-toolkit#20]
Hello,

My list re-order animation is starting as soon as the element from the array is removed.

I want it to wait until the onExit animation for the element is finished.

Is there a way to do so?

https://gist.github.com/marjan2k/9cc9810d07f0517e4c2530f416d97c9f

**Comment by aholachek** [comment]
Hi! 
Unfortunately the library doesn't support that delay at the moment. 
I will look into improving the configurability of the enter and exit transitions this weekend and comment here with any updates.

**Comment by aholachek** [comment]
I'm sorry this took me so long, but I've finally published an update that should allow you to have complete control over the sequencing of the animations. You can provide a new callback `handleEnterUpdateDelete` to the `Flipper` component, which is passed some functions that allows you to handle the timing.
[Here's an example that hopefully makes things clear](https://codesandbox.io/s/4q7qpkn8q0)

I also tried to describe it in the [readme here](https://github.com/aholachek/react-flip-toolkit#advanced-props).

Now that we have this function, `onDelayedAppear` is no longer necessary, so you can just use `onAppear` and implement your preferred order with `handleEnterUpdateDelete`.

I'll keep this issue open for a while in case you have any feedback about the implementation.

**Comment by aholachek** [comment]
Oh, I forgot to mention that you'll have to upgrade to version 6 to use `handleEnterUpdateDelete`
