### ISSUE TITLE
Warning: Unsafe legacy lifecycles in Flipper

### ISSUE THREAD

**Issue by Stanko** [aholachek/react-flip-toolkit#22]
Hello,
First, I want to thank you for the effort and the great library.

On one of the project I'm working on (React 16.2.0) I get the following error:

```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

Flipper uses getSnapshotBeforeUpdate() but also contains the following legacy lifecycles:
  componentWillReceiveProps
  componentWillUpdate

The above lifecycles should be removed. Learn more about this warning here:
https://fb.me/react-async-component-lifecycle-hooks
```

There are no real problems introduced by this issue, I'm more puzzled by it.

Funky thing is that I can't see `componentWillReceiveProps` nor `componentWillUpdate` anywhere in `Flipper.js`. Could it be related to one of the dependencies? As far as I can see you are not using any dependencies that are using react lifecycle. Only other thing I could think of that some other class is also called `Flipper` and that error message is misleading because of it.

<img width="1163" alt="screenshot 2018-09-28 14 41 57" src="https://user-images.githubusercontent.com/776788/46208987-ce2f8c00-c32c-11e8-82d7-d69ce14d3cc0.png">

Cheers and thank you once more!

**Comment by Stanko** [comment]
Heh I'm little bit embarrassed now :) 
It was due `package-lock.json` which was forcing the old version of the library.

Sorry for the false alarm!

**Comment by aholachek** [comment]
I'm glad it resolved easily! Thanks for looking into it.
