### ISSUE TITLE
Flipped children styles not respeced

### ISSUE THREAD

**Issue by carsonjones** [aholachek/react-flip-toolkit#23]
Hi Alex! Great work on the library. We are exploring implementing a similar menu to the one you've demo'd in your [react-stripe-menu](https://github.com/aholachek/react-stripe-menu) example, so many thanks for publicizing your hard work!

I come to you with a bug I've noticed during our own implementation that is present in yours as well. It appears a "flipped" element's children styles no longer apply. This is present when navigating to a non-first (second, third, etc) dropdown. You'll notice that hover styles are missing (no cursor pointer, no color change). See the gif below for details:

![screen recording 2018-10-02 at 10 18 am](https://user-images.githubusercontent.com/5290878/46358434-97a78900-c62c-11e8-8a93-fe21ff5814c3.gif)

Any thoughts on what might be causing this? Any tips on debugging forwarded refs with chrome?

Would love to help you out with this!

**Comment by carsonjones** [comment]
Hold up fam - this might be easier than I imagined. I'm thinking this is a `z-index` problem.

Will report back when I've found more.

**Comment by carsonjones** [comment]
Yep! My theory checked out.

I solved this problem by adding some `z-index` to the inverted element. This Component in  [react stripe menu](https://github.com/aholachek/react-stripe-menu/blob/master/src/DropdownContainer/Components.js#L69) would become:

```js
export const InvertedDiv = styled.div`
  position: ${props => (props.absolute ? "absolute" : "relative")};
  top:0;
  left:0;
  &:first-of-type{ z-index: 1; }
  &:not(:first-of-type) { z-index: -1; }
`
```

This ensures that the active component always appears above in the dom.

@aholachek - I'd be more than happy to open a PR in react-stripe-menu. Let me know!

**Comment by aholachek** [comment]
Thank you for investigating and finding a solution! A pr would definitely be welcome.
