### ISSUE TITLE
Cards not flipping when mapping over an array that renders a card component

### ISSUE THREAD

**Issue by kimfucious** [aholachek/react-flip-toolkit#24]
Hey guys, 

This looks like a nice library.  I'm coming from using React-Flip-Move, which isn't being maintained.

I've scoured the web (nothin on stackoverflow) and pored over the docs and examples here, but can't seem to make things flip with the code below.

In brief I'm mapping over an array that gets filtered when a user clicks on various controls on the page.  So I'm using the length of that array, this.props.projects.length, as the flipKey.

The ProjectListItem is a component that renders a Card for each item in the array.

Everything works with React Flip Toolkit in place: filters work, cards are rendering correctly, etc.) yet nothing flips when the array length changes.

The debugger outputs the following to the console as filters are applied, but that's it:
`The "debug" prop is set to true. All FLIP animations will return at the beginning of the transition.`

It's entirely possible that I'm doing something stupid, but I don't know what.

``` javascript
<div className={classes.projectList}>
                <Flipper debug flipKey={this.props.projects.length}>
                  {this.props.projects.map(project => (
                    <Flipped flipId="projectCard" key={project.project_uid}>
                      <ProjectListItem
                        photoUrl={this.getInitiatorPhotoUrl(
                          project.initiator_uid
                        )}
                        project={project}
                      />
                    </Flipped>
                  ))}
                </Flipper>
              </div>
```

**Comment by aholachek** [comment]
Hi, I think I know what the problem is, it's a bit of a gotcha. The `Flipped` component passes down `data-*` attributes directly to a wrapped JSX element. Unless your `ProjectListItem` is passing through unrecognized props directly to its wrapper DOM element, it is losing those data-* attributes and so `react-flip-toolkit` can't find them. Could you try moving the `Flipped` component inside the render function for `ProjectListItem`?
If `ProjectListItem` already passes through unrecognized props, then let me know and I can think about what else might be going wrong.

**Comment by kimfucious** [comment]
@aholachek awesome!  or should I say, "Flipping Awesome!" 😉 

I moved Flipped into ProjectListItem (surrounding the entire Card) as suggested, keeping Flipper in the parent.

I had to do a slight re-jig in the parent, per the below, replacing the top div (shown in code above) with Flipper and using the **very handy** className prop to get the cards working well with the structure I've created; otherwise, the added div was getting nested and ignoring the flexbox styling.

Thanks mucho for your help getting me on the right track.

``` javascript
              <Flipper
                className={classes.projectList}
                flipKey={this.props.projects.length}
              >
                {this.props.projects.map(project => (
                  <ProjectListItem
                    key={project.project_uid}
                    photoUrl={this.getInitiatorPhotoUrl(project.initiator_uid)}
                    project={project}
                  />
                ))}
              </Flipper>
```
