### ISSUE TITLE
Style the Flipper div?

### ISSUE THREAD

**Issue by FezVrasta** [aholachek/react-flip-toolkit#3]
Is there any way to give some custom CSS to the Flipper div? Specifically, I'd need to set its width to `100%` to make it fit its context.

**Comment by aholachek** [comment]
Hi @FezVrasta, right now there's nothing, but that's an oversight. 

If I added an optional `className` prop to put on the `Flipper` `div`, would that solve your use case? If so I can add it tonight.

**Comment by FezVrasta** [comment]
Yes I think that'd be enough, thanks!

**Comment by aholachek** [comment]
I added the `className` prop ([documented here](https://github.com/aholachek/react-flip-toolkit#props)), thank you for for suggesting it.
