### ISSUE TITLE
backgroundColor Transform

### ISSUE THREAD

**Issue by marjan2k** [aholachek/react-flip-toolkit#37]
Hey,

I guess backgroundColor is not transformed (possibly due to performance issues?).

Is there a trick to do that?

https://codesandbox.io/s/mypv9j96zp

**Comment by aholachek** [comment]
Hi Marjan, did you figure out a solution? I debated adding this to the library originally but then thought I'd limit animations to things that could be gpu-accelerated (opacity and transforms). It would not be super difficult to add in theory, though I'd need to look into how to tween colors without getting the muddy effect in transition.

**Comment by marjan2k** [comment]
Yeah, I didn't want to bother much with the background since I don't really need it.
I was playing around to push the limits your library.

I'm writing a medium article. I'll give kudos to you!
