### ISSUE TITLE
Does spring only work in certain scenarios?

### ISSUE THREAD

**Issue by hlee-cb** [aholachek/react-flip-toolkit#38]
I've gotten this working and it's pretty nifty. Right now I've made an accordion style component and I'm animating scaleY and opacity on the accordion container, using keyframes w/ styled-components. The one thing I can't seem to figure out is the spring prop. I've tried different values for it, and I'm not seeing any difference in effect, even when I slow my animation waaay down. Is there something I'm missing here?

**Comment by aholachek** [comment]
Hi, the spring settings should still be working -- [here's a codepen you can use to play with them](https://codepen.io/aholachek/pen/bKmZbV). If using that codepen as an example doesn't help, I wonder if you could post a code snippet?

**Comment by hlee-cb** [comment]
@aholachek Yeah, I think I must be doing something wrong, because I still can't get it to work. Here's a code snippet:

`import React from "react";
import { Flipper, Flipped } from "react-flip-toolkit";

import {
  CollapsibleSectionWrapper,
  CollapsibleSectionItem,
  CollapsibleSectionItemTitleWrapper,
  CollapsibleSectionItemTitle,
  CollapsibleSectionItemBodyWrapper,
  CollapsibleSectionItemBody
} from "./CollapsibleSection.styled";

const CollapsibleSection = ({
  title,
  startsOpen = false,
  isOpen,
  toggleSection,
  children
}) => {
  if (startsOpen) {
    toggleSection(isOpen);
  }
  console.warn("isOpen in the component", isOpen);
  console.warn("toggleSection", toggleSection);

  return (
    <CollapsibleSectionWrapper>
      <CollapsibleSectionItem>
        <Flipper
          spring="wobbly"
          flipKey={isOpen}
          staggerConfig={{
            section: { reverse: isOpen === false, speed: 0.25 }
          }}
        >
          <CollapsibleSectionItemTitleWrapper>
            <CollapsibleSectionItemTitle onClick={toggleSection}>
              {title}
            </CollapsibleSectionItemTitle>
          </CollapsibleSectionItemTitleWrapper>
        </Flipper>
        <Flipped stagger="section" flipId="body" spring="wobbly">
          {flippedProps => (
            <CollapsibleSectionItemBodyWrapper
              isOpen={isOpen}
              flippedProps={flippedProps}
            >
              <Flipped stagger="content" inverseFlipId="body" scale>
                {flippedProps => (
                  <CollapsibleSectionItemBody flippedProps={flippedProps}>
                    {children}
                  </CollapsibleSectionItemBody>
                )}
              </Flipped>
            </CollapsibleSectionItemBodyWrapper>
          )}
        </Flipped>
      </CollapsibleSectionItem>
    </CollapsibleSectionWrapper>
  );
};

export default CollapsibleSection;
`

and the styled-components file:

`import styled, { keyframes } from "styled-components";

const getCollapsibleBodyKeyFrame = ({ isOpen }) =>
  keyframes`
    from {
      transform: scaleY(${isOpen ? 1 : 0});
      opacity: ${isOpen ? 1 : 0};
    }
    to {
      transform: scaleY(${isOpen ? 0 : 1});
      opacity: ${isOpen ? 0 : 1};
    }
  `;

export const CollapsibleSectionWrapper = styled.div`
  box-sizing: border-box;

  div {
    box-sizing: border-box;
  }
`;

export const CollapsibleSectionItem = styled.div`
  display: grid;
  grid-template-rows: 40px auto;
  grid-template-columns: 100%;
`;

export const CollapsibleSectionItemTitleWrapper = styled.div`
  grid-row: 1 / 2;
  grid-column: 1 / 2;
  display: flex;
  justify-content: space-between;
  align-items: center;
`;

export const CollapsibleSectionItemTitle = styled.h2`
  line-height: 2.5rem;
  margin: 0;
  font-size: 1.75rem;
  font-weight: 700;
  color: #091325;
`;

export const CollapsibleSectionItemBodyWrapper = styled.div`
  grid-row: 2 / 3;
  grid-column: 1 / 2;
  border: 1px solid #ebedf1;
  border-radius: 5px;
  transform-origin: 0 0;
  animation-name: ${props => getCollapsibleBodyKeyFrame(props)};
  animation-duration: 0.25s;
  animation-fill-mode: forwards;
  animation-timing-function: linear;
  padding: 1.5rem;
  background-color: #ffffff;
`;

export const CollapsibleSectionItemBody = styled.div``;
`

**Comment by aholachek** [comment]
I think you are missing the spread operator when you pass in `flippedProps` to your styled component. [You can see an example in the readme here.](https://github.com/aholachek/react-flip-toolkit#wrapping-a-react-component).
So for instance it should be something like `<CollapsibleSectionItemBody {...flippedProps}>` instead of what you have now. Would you mind trying that and letting me know if it helps?

**Comment by hlee-cb** [comment]
Wow, what a silly mistake. Can't believe I didn't notice that one. Seems to be working now, thanks!
