### ISSUE TITLE
Animation from panel to button looks off?

### ISSUE THREAD

**Issue by FezVrasta** [aholachek/react-flip-toolkit#4]
![infopanelanimation](https://user-images.githubusercontent.com/5382443/42657482-2b3d7ca6-85d7-11e8-9be4-8f1f3930b8d7.gif)

As you can see, when the component switches from the "panel view" to the "button view", the button behaves weirdly.

Do you have any idea? May I be doing something wrong?

**Comment by aholachek** [comment]
I'm not sure, sorry. Is it possible that there is a container element that is getting scaled up during the button's animation?

Can you try putting the `debug` prop on the `Flipper` component to cancel the animation after the initial application of `flip` styles? (I haven't really documented it yet but [it's described here](https://github.com/aholachek/react-flip-toolkit#faq)) That might yield some information.

**Comment by FezVrasta** [comment]
![infopanelanimation](https://user-images.githubusercontent.com/5382443/42659793-36d7a5bc-85de-11e8-8573-daef63322aaf.gif)

This is what I get, I don't have any other animation a part for the ones applied by your library

**Comment by FezVrasta** [comment]
Ah fuck, nevermind, I have `transition 0.2s all` on the button component 🙄

**Comment by FezVrasta** [comment]
Now I wonder if I could make the transition be different, so that the panel shrinks to reach the size of the button *and then* it gets replaced by the button 🤔
