### ISSUE TITLE
Cannot debug

### ISSUE THREAD

**Issue by morgs32** [aholachek/react-flip-toolkit#41]
Put `debug` on the `Flipper` component in your [codepen](https://codepen.io/aholachek/pen/mKXBJR) and you will see it breaks because `flip is not a function`...?

**Comment by aholachek** [comment]
Thank you for catching this! I think I see the problem. I'll comment here when I've released a fix.

**Comment by aholachek** [comment]
Thanks again, I just released a patch that should fix this.
