### ISSUE TITLE
index.d.ts gone missing in 6.3.2

### ISSUE THREAD

**Issue by mpontus** [aholachek/react-flip-toolkit#42]
Hi, love this library!

It appears that `index.d.ts` has gone missing during the last release:

https://unpkg.com/react-flip-toolkit@6.3.2/lib/
https://unpkg.com/react-flip-toolkit@6.3.1/lib/

This prevents the module from being loaded in some TypeScript environments:

```
Type error: Could not find a declaration file for module 'react-flip-toolkit'. '/node_modules/react-flip-toolkit/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-flip-toolkit` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-flip-toolkit';`  TS7016
```

Could you please address this issue?

**Comment by aholachek** [comment]
Yikes, the build step must have failed somehow,. [I just published a patch and it seems like the types file is there now](https://unpkg.com/react-flip-toolkit@6.3.3/es/). Thanks very much for pointing this out!

**Comment by mpontus** [comment]
@aholachek Thank you so much for this fantastic tool!
