### ISSUE TITLE
Question: How to transition between two different elements

### ISSUE THREAD

**Issue by carlosagsmendes** [aholachek/react-flip-toolkit#45]
Hi, I found react-flip-toolkit a few months ago but never used it before. 

I remember reading an example of creating transitions between two different elements, but I can't find it.

Can someone provide some guidance on how to create a transition between an item of a drag-and-drop  
[task list and the modal that opens on click with the item details](https://codesandbox.io/s/2z7yw2jwly)?

What I'm trying to achieve visually is similar to the `react-overdrive` image gallery example:

![Image of React Overdrive](https://github.com/berzniz/react-overdrive/raw/master/assets/nextgram-overdrive.gif)

In fact, I tried to use react-overdrive, but then the drag and drop stops working.

Thanks in advance

**Comment by aholachek** [comment]
Hi Carlos, [this pen might be helpful.](https://codepen.io/aholachek/pen/qKeLaN) I'll think about linking to it from the readme!
[Tweening two elements is also described in the readme here.](https://github.com/aholachek/react-flip-toolkit#2-flipped)
I'm going to close this issue for now, but feel free to re open if you have a more concrete question.

**Comment by aholachek** [comment]
Hi, [I made a working version of your sandbox here](https://codesandbox.io/s/k2747z2z13). I had to use the `portalKey` prop as described in the docs, and use a regular React portal instead of `react-modal`, which for some reason takes multiple frames to render and as such breaks `react-flip-toolkit`.
