### ISSUE TITLE
Issue animating inner content in Safari after animation starts

### ISSUE THREAD

**Issue by thomasboyt** [aholachek/react-flip-toolkit#46]
Hi! Really impressed with this library, it puts my extremely hacky attempts at similar behavior in React to shame :)

I ran into an issue in Safari, unfortunately, and I'm not sure what the best way around it is. Basically, I tried to copy your strategy of using the `onStart()` callback to hide incoming content, which allows me to fade content in (in my case I'm just applying a CSS transition after a tick, but using something like `anime.js` has the same issue, I believe). Unfortunately, I'm getting a flash of visible content when I apply this in `onStart()` in Safari. I don't know why it's only an issue in Safari and not Chrome or Firefox, other than Safari's general IE6-ness.

I created a [small test case](https://codesandbox.io/s/zx26l6r5z4) for it (ofc, it only shows the issue in Safari). This issue seems to be really inconsistent, so you might have to play with it a bit (I get the most consistent reproductions in the iOS Simulator).

It's worth noting this isn't an issue if the inner content has `0` opacity to begin with, before the animation even triggers, but in this example, this could only be easily achieved for the open card content, and not the closed content (or otherwise it would be invisible when the page is opened!).

I can only think of a couple possible fixes:

* Do you think there's any good consistent way to run `onStart()` after the DOM has been updated (so that I can apply style to the child elements, whether through `querySelector()` lookups or something like React refs), but before the first actual browser rendering pass? My guess is "no," but I'm secretly hopeful there's like a `setTimeout(fn, 0)` somewhere in the codebase that has inconsistent behavior between browsers and sometimes causes a rendering flush, or something like that.
* Is there a secret better way to structure this that I'm not seeing? I know `<Flipped />` itself can animate opacity, but I need to animate the _content_'s opacity, not the element itself - in this demo, I'd want the boxes to be full opacity, but the text fades in.
* Are there any better ways to initialize the animating-in state?

**Comment by thomasboyt** [comment]
Theory behind the root cause of this, though will concede it's quite late and I've been staring at it for a while, so this may be _totally_ off base:

`onStart()` gets called in the first tick of the internal `onUpdate()` hook, which happens after a `requestAnimationFrame()` call in rehook's `AnimationLoop`. The reason this is an issue in Safari only is that Safari runs RAFs [_after_ the next frame](https://bugs.webkit.org/show_bug.cgi?id=177484), not _before_ as the other browsers do, which causes a flash of the pre-`onStart()` state to be rendered only in Safari. [This tiny example](https://event-loop-tests.glitch.me/raf-timing-test.html) in that bug shows what's basically the exact same issue.

**Comment by aholachek** [comment]
Hi,
Thank you for making this detailed report! I see you're working on your own branch, I'm happy to look at anything you come up with.

Right now, the [onStart function is called when the element starts animating](https://github.com/aholachek/react-flip-toolkit/blob/master/src/flip/animateFlippedElements/index.ts#L362) --which means if it has a staggered delay, `onStart` is not called until the element actually starts moving. However, in retrospect I can't think of too many use cases for this, so I can just call onStart in the same initial frame, in [`initializeFlip`](https://github.com/aholachek/react-flip-toolkit/blob/master/src/flip/animateFlippedElements/index.ts#L398). 

I might just add `onImmediateStart` as a new callback so that I don't affect current behavior. I will test it out and then comment back here.

**Comment by aholachek** [comment]
[Here's a fork of your pen with `onStartImmediate`](https://codesandbox.io/s/9y0qyyj56o), I think it fixes the problem. Please let me know if this seems ok to you and I'll make a minor release.

**Comment by thomasboyt** [comment]
That works, both in the demo and in my actual app! Thank you so much for the fast turnaround. I'll let you know if I find any subtle bugs with it or anything but it seems great :)

**Comment by aholachek** [comment]
Great, [I just released 6.5.0](https://github.com/aholachek/react-flip-toolkit/releases/tag/v6.5.0)
