### ISSUE TITLE
[Feature Request] Working with portal.

### ISSUE THREAD

**Issue by rockmandash** [aholachek/react-flip-toolkit#5]
Hello! Thank you for this amazing library.
Everything is so wonderful, but I want to know if it is possible to compatible with react portal.
Right now, portal will work fine, but the animation will be lost.
Don't know what do you think. Thank you!

**Comment by aholachek** [comment]
This is a good suggestion! I think it should be fairly easy to add, I'll look into it and let you know.

**Comment by rockmandash** [comment]
@aholachek Thank you for your listening!

**Comment by aholachek** [comment]
Hello,
I just published a new version, `3.1.0`, which should allow you to work with portals.
You will have to add a new prop to the `Flipper` component, `portalKey`.
[I documented it at the bottom of the props table for the `Flipper` component.](https://github.com/aholachek/react-flip-toolkit#props)

[Here's a demo of it working](https://literate-fly.surge.sh/portal) 
[And here's the code for the demo](https://github.com/aholachek/react-flip-toolkit/tree/master/demo/src/PortalExample)

If this doesn't match up with what you were hoping for, please let me know and I'll try to improve it!

**Comment by rockmandash** [comment]
@aholachek OMG, WOW.
The working demo is so beautiful!!
Can't believe it's happening!
You are so cool!
Thank you!!!
I will share this project with more people!

**Comment by mattleonowicz** [comment]
@aholachek I have a question regarding this `portalKey`. In TypeScript types I can see that Flipped also has `portalKey` property.
This is not documented but I assume that if I provide it to Flipped, it will only react to Flipper with the same portalKey?
