### ISSUE TITLE
Counter-scaling timing

### ISSUE THREAD

**Issue by doei** [aholachek/react-flip-toolkit#53]
Hi,
This isn't really an issue for this library, but rather me trying to understand how you solved the problem I'm having, I hope it's the right place for it, many thanks if you consider answering :)

I made a pen [here](https://codepen.io/senss/pen/rPaOeM) to show it better.
Basically, counter-scaling child elements doesn't work well for me, because the expansion and counter-expansion don't happen at the same rate, the contents should stay the exact same size, but they're warped in the process.

I understand you used a fork of rebound here, which controls the values to animate directly with javascript rather than let the CSS do its thing, but I'm interested to know if you encountered the problem and what makes your library _not_ have it..

Thanks for reading :)

**Comment by aholachek** [comment]
Feel free to comment if you have any questions or follow ups, I'm going to close this to keep things organized.

**Comment by doei** [comment]
ah of course it's recomputed every tick, I missed that part... Thanks for explaining!
