### ISSUE TITLE
Items not flipping in mapped array

### ISSUE THREAD

**Issue by zapbampow** [aholachek/react-flip-toolkit#54]
I'm assuming I have a very similar problem as [this thread](https://github.com/aholachek/react-flip-toolkit/issues/24). But I've been working on it long enough that it's just time to ask for help.

I'm mapping over an array of objects to display a series of cards, then filtering and sorting which cards to display. I believe I've followed the examples and more or less done what you suggested in the above issue. Yet they still don't flip when I filter or sort them.

At the actual flipper it looks like this:
```
<Flipper flipKey={this.state.flipKey} className="results">
      {this.state.resources.map(resource => {
         return (
           <Flipped flipId={resource.id} key={resource.id}>
             <div className="box">
                 <div className="box-img">
                   <img src={resource.imageUrl} alt={resource.title} />
                 </div>
                 <div className="box-details">
                    <h4>{resource.title}</h4>
                    <p>{resource.primaryCategory}</p>
                    <p>
                    {resource.categories
                       .filter(item => item !== resource.primaryCategory)
                       .slice(0, 2)
                       .reduce((acc, cur) => {
                           return `${acc} | ${cur}`;
                       })}
                    </p>
                </div>
              </div>
           </Flipped>
         );
       })}
</Flipper>
```

Any help you can offer would be greatly appreciated.

[My project on CodeSandbox](https://codesandbox.io/s/r0947j6w2n)

**Comment by aholachek** [comment]
Hi, thanks for posting your test case, it helped me see that you're only 1 tiny tweak away from it working:

`Flipper flipKey={this.state.resources.map(r => r.id).join('')} />`

I think the flipKey prop you are currently using isn't updating correctly.

[Here's a working example ](https://codesandbox.io/s/q3qpqoymow)

**Comment by zapbampow** [comment]
Fantastic! Thank you for the help and for this cool tool. I knew I was close and after an hour I wasn't going to get it. I seriously appreciate it.

**Comment by mikeriley131** [comment]
@aholachek Could you put this solution in the README? Been banging my head for a while trying to figure out why the animations weren't happening. Great package, by the way! Thanks for this.
