### ISSUE TITLE
Flipped Element's Tween causes it to overlap list items

### ISSUE THREAD

**Issue by marjan2k** [aholachek/react-flip-toolkit#55]
Hello,

I'm having difficulty where elements in a list, if they get tweened, they overlap each other sometimes.

The video can explain it better when I click the topmost element at the end.

https://imgur.com/a/sy9j9Rc

**Comment by marjan2k** [comment]
Hi, I confirm I am using 6.5.5.

I found a fix.
For tweening you are adding some styles to the Flipped wrapper's component.  If you provide a prop to add className to the component (add on tween, remove after tween), then I can add zIndex to it.

without zIndex
![image](https://user-images.githubusercontent.com/14934345/51994962-d08f2780-247f-11e9-918b-ee2df7edc5ad.png)

with zIndex
![image](https://user-images.githubusercontent.com/14934345/51995065-ffa59900-247f-11e9-9307-3dc1d53d5bfc.png)

**Comment by marjan2k** [comment]
I did a bit more research.
https://medium.freecodecamp.org/z-axis-html-css-z-index-layout-adventures-2419cefdc2ed

Order of divs are important. A div who comes later in the order, its content will be on top of earlier divs.

In my example, the uppermost item's content gets masked by the 2nd item since the 2nd item's content takes precedence according to div order.

**Comment by aholachek** [comment]
Ah got it. Yes, react-flip-toolkit doesn't do anything special with z-index, it just provides you callback functions to update z index properties on flipped items so that you can customize it as appropriate to your particular animation.
