### ISSUE TITLE
onAppear not called even though hideEnteringElements is called

### ISSUE THREAD

**Issue by afreix** [aholachek/react-flip-toolkit#58]
First off, thanks for this great library! It's really powerful.

When trying to debug an issue I set breakpoints in flip/animateUnflippedElements/index.ts and noticed a scenario in which ```enteringElements``` was inconsistent between the call to ```hideEnteringElements``` and ```animateEnteringElements```. The end result was that my appearing element was invisible, since it had it opacity set to 0 within ```hideEnteringElements```, and onAppear was never called to reset the opacity back to 1.

I'm having trouble reproducing with a smaller scale example, and I'm wondering if you have any ideas. I'm confused as to how it would be possible for ```enteringElements``` to differ between the two callback functions returned by ```animateUnflippedElements```

On a separate note, it might be worth calling out in the docs that the onAppear animation needs to reset opacity, since by default it is set to 0 in ```hideEnteringElements```.

**Comment by aholachek** [comment]
Thank you for making this issue! At first thought I have no idea why this might be happening, you're right that I intended for it to be impossible so I will have to investigate more closely. I probably won't be able to get to investigating the issue until next weekend, but I'll definitely update the docs right now to add mention of onAppear and opacity.

**Comment by afreix** [comment]
For more context, the flow in our application when the issue occurs is along the lines of this:
- We are at a URL /item/{id}
- Button clicked
- Redux action fired to delete element within folder (we are deleting the item at the current URL)
- Redirect to home page URL
- Home page URL has logic and React Router <Redirect /> component that redirects to the appropriate URL (a new item, so /item/{id2}
- Now that we are at a new URL (/item/{id2}). ```id2``` happens to be within a different folder than ```id```, so the folder containing ```id2``` opens. ```onAppear``` is not called for the element that was being rendered by the expanding folder

Some additional things that I noticed during debugging. The exiting item, ```id```, is considered exiting twice by react-flip-toolkit within ```animateUnflippedElements/index,ts```. I also have been debugging the React code because I'm a seeing the render method being called appropriately, but reconciliation is NOT occurring between two separate calls to ```render()```, which might explain why the exiting items appears twice within react-flip-toolkit

**Comment by afreix** [comment]
I've filed a potentially related issue within the React project: https://github.com/facebook/react/issues/14825

**Comment by aholachek** [comment]
Is there any way you could create a test case on Codesandbox for this?

**Comment by afreix** [comment]
I can try do to do that later today

**Comment by afreix** [comment]
I haven't been able to reproduce in an isolated environment, but I've been debugging locally. Looks like it has to do with a JS scoping issue. Changing this line https://github.com/aholachek/react-flip-toolkit/blob/master/src/flip/index.ts#L136 to be synchronous instead of asynchronous fixes the issue, although it results in an undesirable animation.

What is really odd is that after changing to ``finally``` instead of ```then```, ```animateExitingElements``` is called twice but the ```finally``` block is called once. Any ideas? I'm really stumped on this one

**Comment by afreix** [comment]
Wow I feel very silly. It was right in my face the whole time that I was debugging. The problem occurs because we catch the error but never resolve the promise here: https://github.com/aholachek/react-flip-toolkit/blob/master/src/flip/animateUnflippedElements/index.ts#L87

**Comment by afreix** [comment]
Do you have an estimate on when there will be a new release with this bugfix?

**Comment by aholachek** [comment]
tonight! I will comment in this thread when it's live.

**Comment by aholachek** [comment]
It's live in 6.5.7, please let me know if anything is still causing problems. Thanks again for pursuing this.
