### ISSUE TITLE
Spring options codepen is not working with the latest version

### ISSUE THREAD

**Issue by Stanko** [aholachek/react-flip-toolkit#64]
Hello,
It seems that the newest version changed something that breaks spring options codepen https://codepen.io/aholachek/full/bKmZbV/

I just reverted version to 6.0.0 and it works as expected
https://codepen.io/stanko/pen/XGbaew

Cheers!

**Comment by aholachek** [comment]
Oops, it was looking for `proptypes` which are now required for the non-minified `umd` version to work.
I've fixed it, thank you very much for pointing it out!
