### ISSUE TITLE
Cannot read property ownerDocument of null (replacing all elements inside of Flipped)

### ISSUE THREAD

**Issue by owattenmaker** [aholachek/react-flip-toolkit#76]
Hello,

The library here seems amazing, unfortunately I've been unable to get it to work when requesting all new elements inside of the Flipper component. It seems to be that there's a brief interlude where there are no flipped id's that flip is aware of, yet it still tries to run the `animateFlippedElements` function. Searching for it has shown me that there was a recent code change wherein it was suggested (and then merged) to use the `firstElement.ownerDocument` to support iframes instead of `document.body` [here](https://github.com/aholachek/react-flip-toolkit/blob/master/src/flip/animateFlippedElements/index.ts#L166)

If you don't support replacing all elements in the flipped section then at least you should say so in the documentation, so I'm of the belief that this is unintended behavior. 

I've been able to reproduce the issue very easily by slightly modifying the code in your shuffle list example, which I have forked [here](https://codesandbox.io/s/reactfliptoolkit-list-shuffle-example-r0kre). As you can see pressing the shuffle button causes the page to crash.

In case the fork doesn't work properly, here is the flipped component outlined below:
```jsx
const ListShuffler = () => {
  const [data, setData] = useState([1, 2, 3]);
  const shuffleList = () => setData([4,5,6]); 
  // now instead of shuffle, all elements are replaced with new ones
  // i've noticed that this still works if you pass it `[3,5,6]` so the issue is only if all id's get replaced

  return (
    <Flipper flipKey={data.join("")}>
      <button onClick={shuffleList}> shuffle</button>
      <ul className="list">
        {data.map(d => (
          <Flipped key={d} flipId={d}>
            <li>{d}</li>
          </Flipped>
        ))}
      </ul>
    </Flipper>
  );
};
```

My use case for finding this bug was starting with an empty list and then adding stuff in, which also breaks in the above example if you use an initial state of `[]` and then replace that with `[1,2,3]`.

**Comment by petrosalema** [comment]
This is a recent regression. @aholachek, is [working on a fix](ttps://github.com/aholachek/react-flip-toolkit/issues/73#issuecomment-494405702).

**Comment by aholachek** [comment]
Hi @owattenmaker, thank you for making this issue and sorry about the bug. @petrosalema found the source of this issue earlier today and I've just made a bugfix release, `6.6.2`, that should fix it.

I've updated your [test case](https://codesandbox.io/s/reactfliptoolkit-list-shuffle-example-flz13) to use 6.6.2 and it does seem to fix the problem.

**Comment by petrosalema** [comment]
The issue appears fixed. Thank you, @aholachek.

**Comment by owattenmaker** [comment]
Thanks for the quick turnaround! Feel free to mark the issue as closed
