### ISSUE TITLE
Compensate for changing viewport/scroll position across flipKey changes

### ISSUE THREAD

**Issue by diondiondion** [aholachek/react-flip-toolkit#79]
First off, thanks so much for creating this library! It makes creating nice looking transitions between pages amazingly simple, and looks good out of the box. Hats off :)

There's one issue that I wonder whether it could be solved at library level: Taking into account changed scroll positions between transition states.

## Problem description

My use case is very similar to the [guitar](https://react-flip-toolkit-demos.surge.sh/guitar) or [cards](https://react-flip-toolkit-demos.surge.sh/cards) demos: There's both a grid of items, and a detail view once an item has been clicked. The clicked item smoothly transitions to its new position in the detail view. The way this is done in those two demos is that the detail view is essentially a modal view that opens on the same page, with the scroll position staying the same between the two views, ensuring that the transition always happens "in place".

In my use case however (a gatsby page with the layout plugin), clicking an item actually changes the route (the router's location is used as the flipKey) and resets the scroll position to the top of the page, just like navigating a non-SPA would. The result of this is that transitions only look great for items near the top of the grid, but as soon as you've scrolled down the page and click on an item far below, the illusion falls apart, since flip-toolkit uses the absolute position of items on the page to calculate the transition. In other words, clicking an item takes you to the top of the new page, and you see the clicked item transition to its new position from _aaaaaall the way down the page_ to its new position.

Here are some diagrams illustrating the problem:

![Step 1](https://user-images.githubusercontent.com/5636050/58576907-a428c380-8245-11e9-82ce-95ef68ff617b.png)

![Step 2](https://user-images.githubusercontent.com/5636050/58576975-c6badc80-8245-11e9-9b8b-8063b1bf1298.png)

Is this something react-flip-toolkit could handle? In my mind, it'd "just" have to know about the user's new scroll position and account for that for any position calculations.

If it's not something the library can detect by itself, could there be a way to tell the library (or more specifically, a `Flipped` component) the to-be-expected scroll position when this component renders?

Thank you!

**Comment by aholachek** [comment]
Hi, thank you for the detailed description of the problem. I'm surprised it's not working correctly as react flip toolkit uses `getBoundingClientRect` which uses the viewport for measurements-- I would have thought that would take care of scroll position automatically.

I tried to replicate in [this example](https://codesandbox.io/s/simple-reactfliptoolkit-example-2-divs-become-1-v3kqq) which automatically scrolls to the bottom,  but everything seems to be working as I would expect. Could you fork this sandbox and try to replicate the problem so I can understand what needs to be done more clearly?

I might be a little slow in getting back to you this week but this is definitely a use case that the library should support so I'd definitely like to figure out what I'm missing here and fix it if necessary.

**Comment by diondiondion** [comment]
Hi, thanks for the response. You're right... I should've just made my own reproduction sandbox before drawing up diagrams. 😅

I have a busy weekend ahead of me, but I'll create a reproduction as soon as I get around to it. Maybe it's related to how gatsby (and reach-router) handle scroll position on location changes.

**Comment by diondiondion** [comment]
Here's a quick reproduction of the issue using gatsby-starter template as a base (I've added the gatsby layout plugin to keep the `Flipper` mounted between pages): https://codesandbox.io/s/react-flip-toolkit-issue-reproduction-with-gatsby-starter-w70xg

You'll see the issue if you scroll down to the bottom of the page and click the "Go to page 2" link.

If you need an even simpler recreation of the issue that doesn't include gatsby, let me know. This may be related to how/when reach-router updates the scroll position, so maybe it can be recreated only with reach-router.

**Comment by grumd** [comment]
This is actually reproducible without routing or gatsby too.
You can create a list of items, every item with this Flipped:
```js
<Flipped translate flipId={item.id}>
</Flipped>
```
Add a button at the bottom of the page, this button will add 10 more items at the top of the array.
New items will be added, but the scroll will not adjust for it, and the button you just pressed will fly out of the viewport. I'll add a sandbox if needed tomorrow.

**Comment by aholachek** [comment]
Hi @grumd, a reproducible test case would be definitely be helpful

**Comment by grumd** [comment]
@aholachek While trying to make a codesandbox, I realized it was actually a bug in my own code (obscure scrollIntoView usage), so I'm taking my words back.

Awesome lib btw.

**Comment by aholachek** [comment]
Hi @diondiondion, sorry for the delay, I've finally had a chance to take a look at the issue.
[Here is fork of your example that works](https://codesandbox.io/s/react-flip-toolkit-issue-reproduction-with-gatsby-starter-1ik3g).

It turns out that the issue has nothing to do with scroll, rather, for the first tick after the new render, the image dimensions are width: 0, height: 0. I guess the browser only loads and renders the image on the following tick (?) In any case you can tell react-flip-toolkit what the new image dimensions are by adding them to the image's `style` prop.

**Comment by diondiondion** [comment]
HI @aholachek, sorry for the late response. Unfortunately your suggestion doesn't seem to make a difference for me. I noticed that the issue isn't the same across devices – it rarely happens on my Macbook, but always happens on both Chrome and Firefox Mobile on my Android phone (also in your fork of my example). I don't think it's linked to screen size though, seems more like a race condition due to processing power, maybe.

If it's any help, here's a link to my [work-in-progress gatsby project](https://medienwirksam.netlify.com/) where I came across it first. If you open this page on a mobile browser, scroll down the page and select one of the items near the bottom, you'll likely see the image transition into place from below the screen and not from its location on the previous screen.

Sorry for not being able to provide a more solid reproduction strategy, if you need any more information of any kind I'm happy to provide it if it helps to get to the bottom of this. :)

**Comment by diondiondion** [comment]
@aholachek I'm not sure if it's due to changes in my project or in the latest releases of flip toolkit, but this issue doesn't seem to occur for me anymore. 🎉 

Closing this ticket.
