### ISSUE TITLE
staggerConfig.speed is disregarded

### ISSUE THREAD

**Issue by timothy-bailey-redbox** [aholachek/react-flip-toolkit#83]
If I pass in any value to the staggerConfig.default.speed then the stagger speed will always be set to `2`.

The issue is in `src/flip/animateFlippedElements/spring/index.ts` line 58. I suspect the min and max functions need to be reversed so as to clamp the value between `1` and `2`, rather than fixing it to `2`.

**Comment by aholachek** [comment]
yikes, thanks for catching, I'll deploy a patch release tonight and comment here when it's out

**Comment by aholachek** [comment]
This should be fixed in 6.6.5

**Comment by timothy-bailey-redbox** [comment]
Awesome, thanks for that. I've just tried it out and the setting is now working.
