### ISSUE TITLE
Smoother Exit When List is Emptied

### ISSUE THREAD

**Issue by kimfucious** [aholachek/react-flip-toolkit#84]
I ❤️ React Flip Toolkit.  Awesome work!

Is it me, or is the animation a tad jarring when the array backing the `flipkey` is emptied?

What I mean is that when some, but not all of the elements are removed, the animation is lovely, re-arranging the `<li>` elements in a very pleasing fashion.

However, then all of the elements are removed, the entire `<ul>` element is emptied of all `<li>s` in an instant.

I've tried to add some animation on the `<ul>` so that when the array backing the `flipkey` has a length of 0, a "fade out" is added, but it seems that animation is a bit late for the show.

I do ask "Is it me," because it could be something I'm doing stupid, so I wanted to confirm if this happens for anyone else, before I attempt to refactor the code to make the transition smoother in some other way.

**Comment by aholachek** [comment]
Hi @kimfucious, any way you could make a code sandbox to reproduce this problem? Specifically the "animation being a bit late for the show"? I assume you're using the [onExit](https://github.com/aholachek/react-flip-toolkit#callback-props) callback and it's not working correctly?

**Comment by kimfucious** [comment]
Aloha @aholachek 

Thanks for the quick response.

Here's a [sandbox](https://codesandbox.io/s/github/kimfucious/earth-wind-fire) that depicts the behavior that I mentioned.

It's specifically when either "Hide All" is clicked or when the last element has been hidden, where I am seeing that quick exit w/o animation.

Frankly, I didn't read the docs well enough to realize the existence of the `onExit` callback.  My bad 🙄 

What I had done is use a fadeOut class (using animate.css), as can be seen on line 54.  

I'm gonna read up on `onExit` to see how I might apply that to a smoother exit.

**Comment by agriffis** [comment]
@kimfucious I was wrestling with the same thing late last week. react-flip-toolkit animates rearrangements smoothly, but enter and exit are left to the `onAppear` and `onExit` hooks. It took me a while to realize that r-f-t doesn't provide any assistance with the animations, but the hooks are well-designed and it's not hard to use something like `animejs`

Here is a codesandbox: https://codesandbox.io/s/enter-leave-animations-jwmhx 

One thing that still eludes me is how to reconcile the `speed` parameter in react-flip-toolkit with `duration` in `animejs`. I'd like things to be running at approximately the same speeds but I'm not sure how I should calculate it. Do you have any suggestions, @aholachek ?

**Comment by aholachek** [comment]
Hi @agriffis, [this related issue](https://github.com/aholachek/react-flip-toolkit/issues/75) might be useful for you, basically you could use `onSpringUpdate` and handle the tweening yourself.

Otherwise (and this probably isn't clear enough in the docs) you would have to adjust the `stiffness` and `damping` parameters on the `spring` argument, as `speed` is only relevant for the `stagger` config. [Here's an interactive illustration of stiffness and damping](https://codepen.io/aholachek/full/bKmZbV/).

**Comment by kimfucious** [comment]
Thanks @agriffis

Your sandbox showed me how to implement the onExit callback.

The problem is that I hilariously don't know what I'm doing.

As the project I'm working on already uses Animate.css and bootstrap, which uses jQuery by default, I thought I'd try something _easy_ like:

```js
  const onExit = (el, i, removeElement) => {
    const val = el.getAttribute("data-flip-id");
    $(`[data-flip-id=${val}]`).addClass("animated fadeOut");
    return removeElement;
  };
```
This does run the `onExit` callback, but the behavior is not as expected.  For example, multiple elements are getting removed, when only trying to remove one.  And elements aren't coming back when I want them to.  

I suspect this is because I'm directly manipulating the DOM and not using refs, but as I mentioned, I don't know what I'm doing here 😄 

I've left the mis-behaving code in my [sandbox](https://codesandbox.io/s/github/kimfucious/earth-wind-fire), with the hopes that someone may have the time and patience to check it out.  

To see the expected behavior (of the example, not the desired smooth exit animation), remove the `onExit` prop on the `Flipped` element.

**Comment by agriffis** [comment]
@aholachek Thanks, that's helpful.

Regarding `onSpringUpdate` I think there's a gotcha when transition to or from zero elements, right? In that case there are no elements being flipped, so there's no spring...

**Comment by aholachek** [comment]
@agriffis very good point. For v7, which should hopefully be ready in a couple of weeks, I am working on adding a modified version of [this pr](https://github.com/aholachek/react-flip-toolkit/pull/82) so that you'll be able to create springs with the same settings as your flip animations for enter/exit animations.

**Comment by agriffis** [comment]
@kimfucious I haven't looked at your sandbox, but a couple things for you...

First, you don't need to look up the element by id, because you already have the element. Second, you need to call `removeElement` when it has finished fading out. This should be timed according to how long your `animated fadeOut` takes.

For example:

```javascript
const onExit = (el, i, removeElement) => {
    el.classList.add('animated', 'fadeOut')
    setTimeout(removeElement, 500)  // if fading out will take 500 milliseconds
}
```

Hope that gets you pointed in the right direction!

**Comment by kimfucious** [comment]
Thanks mucho @agriffis for the assist.

Unfortunately, I'm getting the same behavior with your suggested onExit as I was with my initial attempt.

[This one](https://codesandbox.io/s/this-one-works-0n3e3) works and [this one](https://codesandbox.io/s/github/kimfucious/earth-wind-fire) doesn't.

It could very well be something I'm doing stupid somewhere else that I haven't picked up on yet.

**Comment by agriffis** [comment]
@kimfucious Try this https://codesandbox.io/s/earth-wind-fire-wmil1

Mainly note how it calls removeElement from setTimeout after the fade out

**Comment by kimfucious** [comment]
@agriffis you are a ⭐️ !

Taking a look at your excellent handy work, I've noted some refactoring of the example.

If I simply replace the `onExit` function with yours, I still have the same issue as before, which leads me to believe that the issue lies elsewhere in my implementation.

I'll take a closer look at your refactored example to hopefully learned what I'd messed up.

Thanks much for taking the time to help me out on this.
