### ISSUE TITLE
[Core] Rename onUpdate() to update()

### ISSUE THREAD

**Issue by atomiks** [aholachek/react-flip-toolkit#85]
I notice you're nearing the 7.0 release potentially and just thought I'd add this suggestion here. 😄 

`onUpdate()` to me seems more like a callback func I'd pass to the config object rather than a method I'd call on the instance, so I feel `update()` is more fitting. What do you think?

**Comment by aholachek** [comment]
Yes, that makes sense. I think I called it that because of how I use the equivalent method in React, in `componentDidUpdate`. I'll update it (heh) now.

**Comment by aholachek** [comment]
This is released in v7, and I've published the core of the library to [`flip-toolkit`](https://github.com/aholachek/react-flip-toolkit/tree/master/packages/flip-toolkit). Please let me know if you find anything wonky or have other suggestions.
