### ISSUE TITLE
List Transition demo is broken

### ISSUE THREAD

**Issue by apswak** [aholachek/react-flip-toolkit#87]
First of all thanks for all your efforts - great module!

I've been working through the examples/tutorials and got to the [List Transition](https://alex.holachek.com/rft-tutorial/#0) one which seems to be broken on any environment other than codesandbox. I've even copied over file by file incase I'd made any errors along the way but the animations are still broken. Also tried everything in the trouble shooting section but everything internally seems fine.

Reproduction steps:

1. `create-react-app broken-animation && cd broken-animation && yarn add react-flip-toolkit && yarn start`
2. Copy the `index.js` from [here](https://codesandbox.io/s/wnnxl223n8) into the `./src/index.js` file from newly created project. Change `import "./styles.css";` to `import "./index.css";` to account for the file name difference. Then again copy `./styles.css` from codesandbox into `./src/index.css` in new project.

If anyone has any idea what's going on any help greatly appreciated!

**Comment by aholachek** [comment]
Hi, while I'm not sure what's going wrong with the transferred code, you can download a zip file containing the project directly from codesandbox using this button:
<img width="483" alt="Screen Shot 2019-07-13 at 6 40 24 PM" src="https://user-images.githubusercontent.com/3680488/61177233-c11f1900-a59d-11e9-84f8-0a2654fd752f.png">

[There's also a similar example up on codepen where all the code is on one page if that's easier to copy over](https://codepen.io/aholachek/pen/jvvarq)

**Comment by apswak** [comment]
Thanks for the prompt response @aholachek. For anyone else having the same issue; the demo uses `react-flip-toolkit` `v5.x.x` whereas a fresh install atm sets it at `v6.6.9`. I've followed it up and noticed the breaking change happens between `v6.6.5` and `v6.6.6`. No idea what the fix is so I'll have to stay on this version for now. Thanks again

**Comment by aholachek** [comment]
If I update the codesandbox and set react flip toolkit version to `latest` (6.6.9), it still works: [example](https://codesandbox.io/s/wnnxl223n8f) so I'm not sure the version bump was the issue. However, 6.6.6 was when I moved over to a new bundling strategy so that does seem suspicious. If you find out any additional information about this please let me know.

**Comment by aholachek** [comment]
With the release of 7.0.0, as far as I can tell this is fixed.
