### ISSUE TITLE
Remove incorrect types reference

### ISSUE THREAD

**Issue by daaku** [aholachek/react-flip-toolkit#91]
Looks like this is incorrect: https://github.com/aholachek/react-flip-toolkit/blob/master/packages/react-flip-toolkit/package.json#L10. Removing this line allows typescript to correctly find the relevant types automatically.

This is in version `7.0.2`.

**Comment by aholachek** [comment]
This should be fixed in `7.0.3` thanks to #92
Please let me know if you still see any issues.

**Comment by daaku** [comment]
Fix looks good. Thanks for the quick turnaround!
