### ISSUE TITLE
Typescript error: Cannot find module '../forked-rebound/types'.

### ISSUE THREAD

**Issue by llacorne** [aholachek/react-flip-toolkit#94]
Hello,

I use react flip toolkit in my project and I have a typescript error.

`node_modules/react-flip-toolkit/lib/FlipToolkit/Spring/index.d.ts:6:116 - error TS2307: Cannot find module '../forked-rebound/types'.`

You can reproduce this error in the following repository https://github.com/llacorne/friendly-telegram.

You can see the error with command: `tsc --lib ESNext ./index.ts`

Did I do something wrong ?

Thanks.

**Comment by aholachek** [comment]
Thank you for pointing this out, and providing a test case.
I recently did some refactoring and must have messed up the types then. I've just released 7.0.5 which seems to work on your repo -- please let me know if you still have any issues.
Thank you again!

**Comment by llacorne** [comment]
Thank you !
